Making TREX build system more robust. Prevent bugs caused by not being in the right directory, and also actually fail is the tests fail.
git-svn-id: https://svn.code.sf.net/p/personalrobots/code/pkg/trunk@12256 f5854215-dd47-0410-b2c4-cdd35faa7885

Former-commit-id: 6d846f6f29345e769d350fa83a60f723ad50710b

diff --git a/3rdparty/trex/make_trex b/3rdparty/trex/make_trex
--- a/3rdparty/trex/make_trex
+++ b/3rdparty/trex/make_trex
@@ -1,13 +1,17 @@
 #!/bin/bash
+#This file is needed, to force the use of bash, so devConfig can be sourced.
 
 if [ `uname` = Darwin ]; then
   export DYLD_BIND_AT_LAUNCH=YES
 fi
 
-# PLASMA_HOME is required to build the PLASMA NDDL.jar
-source devConfig
+#Have to be here to source it.
+cd `rospack find trex`
 
-cd TREX
+# PLASMA_HOME is required to build the PLASMA NDDL.jar
+source `rospack find trex`/TREX/devConfig
+
+cd `rospack find trex`/TREX
 
 # Build the nddl jar file used to parse input files
 jam $ROS_PARALLEL_JOBS -q nddl.jar
@@ -17,28 +21,38 @@ if [ $? -ne 0 ] ; then
     exit 1
 fi
 
-# Build the debug version
-if [ `uname` = Darwin ]; then
-  jam $ROS_PARALLEL_JOBS -q libTREX_g.dylib
-else
-  jam $ROS_PARALLEL_JOBS -q libTREX_g.so
-fi
 
-if [ $? -ne 0 ] ; then
-    echo "Jam of libTREX_g.so failed."
+
+function run_jam {
+  echo $1
+  if [ `uname` = Darwin ]; then
+    jam $ROS_PARALLEL_JOBS -q $1.dylib
+  else
+    jam $ROS_PARALLEL_JOBS -q $1.so
+  fi
+  if [ $? -ne 0 ] ; then
+    echo "Jam of $1 failed."
+    exit $2
+  fi
+}
+
+
+if [ "$1" = "test" ] ; then
+  cd `rospack find trex`/TREX/agent/test
+  jam agent-module-tests
+  if [ $? -ne 0 ] ; then
+    echo "Test file creation failed."
     exit 1
-fi
+  fi
+  jam run-agent-module-tests
+  if [ $? -ne 0 ] ; then
+    echo "Tests failed."
+    exit 1
+  fi
 
-# Build the optimized version
-if [ `uname` = Darwin ]; then
-  jam $ROS_PARALLEL_JOBS -sVARIANTS=OPTIMIZED -q libTREX_o.dylib
 else
-  jam $ROS_PARALLEL_JOBS -sVARIANTS=OPTIMIZED -q libTREX_o.so
-fi
-
-if [ $? -ne 0 ] ; then
-    echo "Jam of libTREX_o.so failed."
-    exit 2
+  run_jam "libTREX_g" 1
+  run_jam "libTREX_o" 2
 fi
 
 cd ../
