Fix for bug 248: no build failure if jam fails.
git-svn-id: https://svn.code.sf.net/p/personalrobots/code/pkg/trunk@3708 f5854215-dd47-0410-b2c4-cdd35faa7885

diff --git a/3rdparty/trex/make_trex b/3rdparty/trex/make_trex
--- a/3rdparty/trex/make_trex
+++ b/3rdparty/trex/make_trex
@@ -8,7 +8,18 @@ cd TREX
 # Build the debug version
 jam -q libTREX_g.so
 
+if [ $? -ne 0 ] ; then
+    echo "Jam of libTREX_g.so failed."
+    exit 1
+fi
+
 # Build the optimized version
-jam -q libTREX_o.so
+jam -sVARIANTS=OPTIMIZED -q libTREX_o.so
+
+if [ $? -ne 0 ] ; then
+    echo "Jam of libTREX_o.so failed."
+    exit 2
+fi
 
 cd ../
+
