Build nddl.jar too
git-svn-id: https://svn.code.sf.net/p/personalrobots/code/pkg/trunk@5649 f5854215-dd47-0410-b2c4-cdd35faa7885

diff --git a/3rdparty/trex/make_trex b/3rdparty/trex/make_trex
--- a/3rdparty/trex/make_trex
+++ b/3rdparty/trex/make_trex
@@ -5,6 +5,14 @@ source devConfig
 
 cd TREX
 
+# Build the nddl jar file used to parse input files
+jam -q nddl.jar
+
+if [ $? -ne 0 ] ; then
+    echo "Jam of nddl.jar failed."
+    exit 1
+fi
+
 # Build the debug version
 jam -q libTREX_g.so
 
