Test PLASMA in addition to TREX in the trex package. This is because we now have our own branch of PLASMA and as a result, it is not autotested at NASA. So, if we don't test it here at WG, it will never be autotested.
git-svn-id: https://svn.code.sf.net/p/personalrobots/code/pkg/trunk@19550 f5854215-dd47-0410-b2c4-cdd35faa7885

Former-commit-id: c10f9f079f8af46396053dd240f319d23f80e866

diff --git a/stacks/trex/trex/make_trex b/stacks/trex/trex/make_trex
--- a/stacks/trex/trex/make_trex
+++ b/stacks/trex/trex/make_trex
@@ -54,15 +54,21 @@ function run_jam {
 
 
 if [ "$1" = "test" ] ; then
+  cd `rospack find trex`/PLASMA/src/PLASMA
+  jam run-checkin-tests
+  if [ $? -ne 0 ] ; then
+    echo "PLASMA tests failed."
+    exit 1
+  fi
   cd `rospack find trex`/TREX/agent/test
   jam agent-module-tests
   if [ $? -ne 0 ] ; then
-    echo "Test file creation failed."
+    echo "TREX test file creation failed."
     exit 1
   fi
   jam run-agent-module-tests
   if [ $? -ne 0 ] ; then
-    echo "Tests failed."
+    echo "TREX tests failed."
     exit 1
   fi
 
