Fixed build problems.
git-svn-id: https://svn.code.sf.net/p/personalrobots/code/pkg/trunk@929 f5854215-dd47-0410-b2c4-cdd35faa7885

diff --git a/exec_trex/Jamfile b/exec_trex/Jamfile
--- a/exec_trex/Jamfile
+++ b/exec_trex/Jamfile
@@ -1,6 +1,10 @@
 SubDir exec_trex ;
 
-if ! $(exec_trex_READY) {
+if ! $(ROS_PACKAGE_PATH) {
+     	echo "" ; echo "" ;
+        echo "ERROR: You need to set ROS_PACKAGE_PATH." ;
+	echo "" ; echo "" ;
+} else if ! $(exec_trex_READY) {
 
 	# All this ROS and PR related stuff needs to be cleaned up. As it stands, it will not have any make integration
 	# for when ROS or Pr change. Also, the declarations at this level force linkage of more than should otherwise
@@ -11,12 +15,12 @@ if ! $(exec_trex_READY) {
 			[ FDirName $(ROS_ROOT) 3rdparty xmlrpc++ libXmlRpc.a ]
 			[ FDirName $(ROS_ROOT) util rosthread lib librosthread.a ]
 			[ FDirName $(ROS_ROOT) util rostime lib librostime.a ]
-			[ FDirName $(PR_ROOT) 3rdparty player player lib libwavefront_standalone.so ]	       
-			[ FDirName $(PR_ROOT) util transforms rosTF lib
+			[ FDirName $(ROS_PACKAGE_PATH) 3rdparty player player lib libwavefront_standalone.so ]	       
+			[ FDirName $(ROS_PACKAGE_PATH) util transforms rosTF lib
    			  librosTF.a ]
-			[ FDirName $(PR_ROOT) util transforms libTF lib libTF.a
+			[ FDirName $(ROS_PACKAGE_PATH) util transforms libTF lib libTF.a
    			]
-			[ FDirName $(PR_ROOT) 3rdparty newmat10 newmat newmat10
+			[ FDirName $(ROS_PACKAGE_PATH) 3rdparty newmat10 newmat newmat10
    			  libnewmat.a ] ;
 
 	# Include directories for ROS. Can obtain from rospack export/cpp/cflags roscpp
@@ -28,10 +32,10 @@ if ! $(exec_trex_READY) {
    	SubDirHdrs $(ROS_ROOT) std_msgs msg cpp ;
 	SubDirHdrs $(ROS_ROOT) std_srvs srv cpp ;		
 	
-	SubDirHdrs $(PR_ROOT) 3rdparty player player include player-2.2 ;
-	SubDirHdrs $(PR_ROOT) util transforms rosTF include ;
-	SubDirHdrs $(PR_ROOT) util transforms libTF include ;
-	SubDirHdrs $(PR_ROOT) 3rdparty newmat10 newmat ;
+	SubDirHdrs $(ROS_PACKAGE_PATH) 3rdparty player player include player-2.2 ;
+	SubDirHdrs $(ROS_PACKAGE_PATH) util transforms rosTF include ;
+	SubDirHdrs $(ROS_PACKAGE_PATH) util transforms libTF include ;
+	SubDirHdrs $(ROS_PACKAGE_PATH) 3rdparty newmat10 newmat ;
 
 	# GNU Library include directories
 	SubDirHdrs / usr include gtk-2.0 ;
